sudo: required
services:
  - docker

before_install:
  - docker build -t kaushik1986/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kaushik1986/docker-react npm run test -- --coverage

